### ISSUE TITLE
julia 1.03 install error

### ISSUE THREAD

**Issue by danielchen26** [JuliaDebug/Debugger.jl#170]
Here is what I get:

`  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> add Debugger
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DiffBase [c5cfe0b6]:
 DiffBase [c5cfe0b6] log:
 ├─possible versions are: [0.0.1-0.0.5, 0.1.0, 0.2.0, 0.3.0-0.3.2] or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with NLsolve [2774e3e8] to versions: [0.0.1-0.0.5, 0.1.0, 0.2.0, 0.3.0-0.3.2] — no versions left
   └─NLsolve [2774e3e8] log:
     ├─possible versions are: [0.1.0-0.1.4, 0.2.0, 0.3.0-0.3.3, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.7.0-0.7.3, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0, 0.12.0-0.12.1, 0.13.0, 0.14.0-0.14.1, 1.0.0-1.0.1, 1.1.0-1.1.1, 2.0.0-2.0.1, 2.1.0, 3.0.0-3.0.1, 4.0.0] or uninstalled
     └─restricted to versions 3.0.1 by an explicit requirement, leaving only versions 3.0.1

(v1.0) pkg>`

**Comment by timholy** [comment]
This is not specific to Debugger; you could add any new package and you'll get the same error. You can see the problem comes from some interaction between NLsolve and DiffBase, try removing one or both packages.

If you need further guidance, please ask on [discourse](https://discourse.julialang.org/) or file an issue at Pkg.jl.
