### ISSUE TITLE
How to enter debug mode again after changing a variable in REPL?

### ISSUE THREAD

**Issue by friederikemeier** [JuliaDebug/Debugger.jl#253]
Hi!

I am really stuck and just hope, someone will answer my dumb question.
I am trying to debug in julia for the first time... I'm an engineer and not used to using the console that much.

So I watched this debugger demo:
https://www.youtube.com/watch?v=SU0SmQnnGys

It took me a lot of further googling to realize that he uses a ` to get from the debug mode to normal mode, in order to change a variable.
Now that he's changed the variable, he uses a magic trick to enter debug mode again...

I would like to know, how he does it?
Thanks a lot already to anyone reading this and hopefully answering?

**Comment by friederikemeier** [comment]
Ok, accidentally found the answer.. How is this such a hidden information?

I used backspace.

May this help the next one :)

**Comment by timholy** [comment]
Thanks for reporting this, @friederikemeier! I've reopened this because I agree it needs to be better documented. See if the pull request in #254 helps. (If you're unfamiliar with GitHub, click on "Files changed" to see what I changed.)

If you notice more of these issues, please submit more issues or add improvements of your own. The way I made that change was to navigate to the Debugger.jl home page, entered the `src` directory and then the `commands.jl` file, and clicked the pencil icon. More docs are [here](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository). Any of your changes will be vetted by a developer before being merged, so you can't possibly break anything.

**Comment by friederikemeier** [comment]
Thank you so much! This will definitely help the next one!
And actually I didn't know I could edit files on github without forking the repo, also nice new knowledge :)
