### ISSUE TITLE
Any plans to build something for jupyter qtconsole?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaDebug/Debugger.jl#278]
related to #125 

Will Jupyter and qtconsoles just never be supported by julia's debugger?

From a user perspective it looks like as Jupyter communicates with an underlying Julia REPL (you can exeucte things like ; and ]). Hence it seems plausible, that also the repl based debugger could be supported...
Also browser-based sessions like when using binder can not easily debug failures in plots or the like, as you only have access to the plots via jupyter/qtconsole. It would be tremendously helpful to be able to debug here directly.

If this is entirely not possible, can someone summarize the reasons to better understand this ongoing limitation when comparing Julia to Python?

thank you very much for your support

**Comment by timholy** [comment]
I haven't looked at it, but it would need someone to do the work. Is there a champion who advances Jupyter's capabilities for Julia? The VSCode & Juno teams are the ones who added JuliaInterpreter support to those ecosystems. I don't think there is anyone working directly on JuliaInterpreter.jl & Debugger.jl who uses Jupyter heavily. From my personal perspective, just fixing bugs and maintaining a package that dives deep into Julia's internals (and so needs to fix breakages with any new Julia release) is enough maintenance burden for me (https://github.com/JuliaDebug/JuliaInterpreter.jl/commits/master). I very much doubt the existing crew has any intention of implementing this.

But if it's easy to do, someone who uses Jupyter should step up and do it. JuliaInterpreter has a quite-well documented debug API, and at this point it's been tested with several different backends, so I doubt anyone would need to dig into the internals of the actual debugging and it would all be about Jupyter interaction.

**Comment by KristofferC** [comment]
This is just a frontend for the debugger in JuliaInterpreter implemented for the Julia REPL. Another frontend is the one in vscode. For jupyter notebook, someone would have to implement a frontend for that. It's likely some of the code here could be used as inspiration but it is unlikely to be implemented here.

**Comment by pfitzseb** [comment]
I think the most promising approach is [JupyterLab's debugger UI](https://github.com/jupyterlab/debugger), which is based on Microsofts Debug Adapter Protocol, for which we (kinda) have an implementation already.

**Comment by schlichtanders** [comment]
thank you all!
I am using JupyterNotebook/JupyterLab significantly for workshop-like presentations. With binder it is so nice to let everyone have their own little julia session, with maximal little maintenance effort.

@timholy Thank you for the awesome work you do, also with JuliaInterpreter.jl It looks relatively straightforward to build a similar debugger support on top of it for Jupyter, and @pfitzseb thank you for the pointer to JupyterLab's debugger. That looks pretty awesome, especially because of the similarity to the VSCode extension. Thanks @KristofferC for pointing out that the right place would be another package, maybe borrowing code from the VSCode extension.

So I would be glad if someone steps up to build the Jupyter support, and indeed maybe that someone is going to be me. I am not sure whether I'll find the time, but I would really like to see such a Jupyter support.
Thank you all for the valuable input!

**Comment by davidanthoff** [comment]
I [looked into this](https://github.com/JuliaLang/IJulia.jl/issues/903) a while ago, and I think the right way to solve this is definitely what @pfitzseb hinted at: essentially use https://github.com/julia-vscode/DebugAdapter.jl, our existing debug adapter protocol implementation and hook that up with https://github.com/jupyterlab/debugger. The communication layer for DebugAdapter.jl uses https://github.com/julia-vscode/JSONRPC.jl, and when I wrote that I tried to design it in such a way that it should be fairly easy to switch out the actual transport layer for something else via multiple dispatch. That is essentially what needs to be done here: send the debug adapter protocol messages via the Jupyter message protocol rather than on-the-wire JSON-RPC. And I think potentially also add support for a few additional Jupyter specific debug messages, but I'm not entirely sure.

The place where all of this would have to start is IJulia.jl, I believe.

In terms of bandwidth: I have none for this at the moment, and don't expect that situation to improve in the foreseeable future. Once we've made it through the pandemic and things are back to a slightly more normal situation, maybe :)
